In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import numpy as np

In [32]:
model = Sequential([
    Dense(10, activation='relu', input_shape=[4]),
    Dense(3, activation='linear')
])


In [33]:
model.compile(optimizer='adam', loss='mse')

In [43]:
state = [1, 2, 3, 4]
memory = [state, state, [4, 3, 2, 1], state]

In [44]:
sample = np.array(memory)

In [45]:
sample

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [4, 3, 2, 1],
       [1, 2, 3, 4]])

In [46]:
g = 2*np.max(model.predict(sample), axis=1) * np.bitwise_not([False, False, False, False])

In [47]:
g + np.array([2, 1, 2, 2])

array([4.43192053, 3.43192053, 3.39805698, 4.43192053])

In [48]:
ind = np.random.randint(0, 4, 2)

In [53]:
ind = np.array([0, 2])

In [54]:
sample[ind, np.array([3, 1])]

array([4, 3])